/**
 * Convenience aliases derived from the generated schema types.
 *
 * `database.types.ts` is generated by `npm run db:types` and must not be edited by
 * hand -- every regeneration overwrites it. Anything hand-written that needs to
 * outlive a regeneration lives here instead, derived from `Database` so it stays
 * correct automatically when the schema changes.
 */
import type { Database } from "./database.types";

export type Json = Database["public"]["Tables"]["submissions"]["Row"]["answers"];

export type SubmissionRow = Database["public"]["Tables"]["submissions"]["Row"];
export type SubmissionInsert = Database["public"]["Tables"]["submissions"]["Insert"];
export type SubmissionUpdate = Database["public"]["Tables"]["submissions"]["Update"];

export type ProfileRow = Database["public"]["Tables"]["profiles"]["Row"];

export type DisabilityType = Database["public"]["Enums"]["disability_type"];
export type SurveyTypeEnum = Database["public"]["Enums"]["survey_type"];
export type GenderEnum = Database["public"]["Enums"]["gender_type"];
export type AppRole = Database["public"]["Enums"]["app_role"];

/**
 * One row as returned by `list_submissions()`, which hands back camelCase JSON rather
 * than table columns so the dashboard does not have to translate on every render.
 */
export interface SubmissionListItem {
  id: string;
  childName: string;
  educationGrade: string;
  gender: GenderEnum;
  schoolName: string;
  birthDate: string;
  checkupDate: string;
  parentName: string;
  checkerName: string | null;
  isTalented: boolean;
  talentPercent: number;
  isDisabled: boolean;
  disability: DisabilityType | null;
  disabilityPercent: number | null;
  surveyType: SurveyTypeEnum;
  satisfactionPercent: number | null;
  answers: number[];
  locale: string;
  isDemo: boolean;
}

export interface SubmissionListPage {
  total: number;
  pageSize: number;
  offset: number;
  items: SubmissionListItem[];
}

/** The subset of a submission that `get_report()` returns to an anonymous holder. */
export interface ReportData {
  id: string;
  childName: string;
  educationGrade: string;
  gender: GenderEnum;
  parentName: string;
  checkerName: string | null;
  checkerTitle: string | null;
  birthDate: string;
  checkupDate: string;
  schoolName: string;
  isTalented: boolean;
  talentPercent: number;
  isDisabled: boolean;
  disability: DisabilityType | null;
  disabilityPercent: number | null;
  surveyType: SurveyTypeEnum;
  answers: number[];
  locale: string;
}
